# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language: English
en:
  languageCode: en-us
  languageName: English
  weight: 1
  contentDir: content/en

# Second language: Chinese (Simplified)
zh:
  languageCode: zh-Hans
  languageName: 中文
  weight: 2
  contentDir: content/zh
  title: 李思思实验室
  params:
    description: 深圳大学 RNA免疫实验室
